# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20241023-220138-cold-relish

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

#pipeline: null
pipeline: 
  - name: WhitespaceTokenizer #tokens
  - name: RegexFeaturizer #expresiones regulares
  - name: LexicalSyntacticFeaturizer #prefijos-sufijos-combinaciones
  - name: CountVectorsFeaturizer #texto en vectores [1,1,1]
  - name: CountVectorsFeaturizer #n-gramas caracteres, h-ho-hol
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier #modelo principal de RASA
    epochs: 100
#    constrain_similarities: true
#  - name: EntitySynonymMapper #sinonnimos de entidades
#  - name: ResponseSelector #seleccionar respuestas predefinidas
#    epochs: 100
#    constrain_similarities: true
  - name: FallbackClassifier #mensajes
    threshold: 0.7 #0.7 0.3
    ambiguity_threshold: 0.1
  - name: RegexEntityExtractor
    patterns:
      - name: number
        pattern: '\\d+'

policies:
  - name: MemoizationPolicy #memoriza secuencias exactas
  - name: RulePolicy #reglas especificas
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
  - name: UnexpecTEDIntentPolicy #respuestas que el modelo no predice bien
    max_history: 5
    epochs: 100
  - name: TEDPolicy #conversaciones largas memoria
    max_history: 5
    epochs: 100
#    constrain_similarities: true

# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
#policies: null

# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
